Prepare for DragGestureHandler
software-mansion/react-native-gesture-handler pull request #1035
Opened 2020-04-15 10:20 UTC by ShaMan123

This is the first PR preparing the repo for #963 
It enhances the registry and the interaction controller.
Build passes.
@osdnk Once this will be merged I'll create the next.

2020-09-09 11:02 UTC, jakub-gonet requested changes
Thanks for the PR!

Left a few comments. I'd love a more detailed description of this PR, the current one isn't really self-contained and feels a bit enigmatic. 

Also, we have a merge conflict here but should be fairly easy to resolve.

2020-09-09 11:12 UTC, jakub-gonet commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
Oh, actually I think this may be related to the fact that RNGH was distributed as a standalone Android library.

2020-09-09 11:33 UTC, jakub-gonet commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
I talked with @kmagiera and we agreed that we won't distribute RNGH as an android library so this is safe to delete.

2020-10-08 06:30 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
This was for the android impl. 
The commits I've pushed to the example app uses the android impl for drag and drop tests between 2 apps, one built using RN and one built natively. So this is why I left the interface intact.

2020-10-08 06:47 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerInteractionManager.java
> +}
cdba65c

2020-10-08 06:58 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
I wanted to test a drag and drop gesture between RN built app to a standard app to test whether it's possible and it is.
Will be introduced in later PRs.

2020-10-08 06:58 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
Resolved?

2020-10-08 07:01 UTC, ShaMan123 commented on android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRegistry.java
> +  @UiThread
Removed annotation.
The assertion is made in RN core code when calling `UIManagerModule.resolveView`.
f7616e3

2020-10-08 07:01 UTC, ShaMan123 commented on android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRegistry.java
> +    } else {
f7616e3

2020-10-08 07:07 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mHandlersForView.get(view);
I don't see a problem here, this was the logic before my PR. See [code](https://github.com/software-mansion/react-native-gesture-handler/blob/master/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java#L26).
I've simply refactored it.
Plus, the registry is in charge of dropping handlers when a view gets unmounted and drops unmounted handlers so this is a no opt.

2020-10-08 07:10 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mViewForTag.get(handler.getTag());
I don't see a problem....

I don't see a problem here, this was the logic before my PR. See [code](https://github.com/software-mansion/react-native-gesture-handler/blob/master/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java#L26).
I've simply refactored it.
Plus, the registry is in charge of dropping handlers when a view gets unmounted and drops unmounted handlers so this is a no opt.

_Originally posted by @ShaMan123 in https://github.com/software-mansion/react-native-gesture-handler/pull/1035#discussion_r501492816_

2020-10-08 07:12 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mHandlersForView.get(view);
This registry is used by the android library alone.

2020-10-08 07:12 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mViewForTag.get(handler.getTag());
This registry is used by the android library alone.

_Originally posted by @ShaMan123 in https://github.com/software-mansion/react-native-gesture-handler/pull/1035#discussion_r501495096_

2020-10-08 07:13 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mHandlersForView.get(view);
OK so you saw there's no detaching here for the native library. I see what you mean now.

2020-10-08 07:18 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
>  public class GestureHandlerRegistryImpl implements GestureHandlerRegistry {
There is the need for the interface because it is used in the native code in `lib`

2020-10-08 07:56 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mHandlersForView.get(view);
cef5d34

2020-10-08 07:56 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerRegistryImpl.java
> +    return mViewForTag.get(handler.getTag());
cef5d34

2020-10-08 07:57 UTC, ShaMan123 commented on android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerInteractionManager.java
> +package com.swmansion.gesturehandler;
For functionality that will be introduced in the next PRs and for the android library (which I now understand has been deprecated - I don't see why, it's rock solid).
Plus, it makes more sense and it is cleaner this way, managing RN logic separately from gesture logic.

2020-10-08 09:16 UTC, ShaMan123 commented
update PR description

2021-03-29 17:38 UTC, nandorojo commented
Hey all, is there any intention to continue this PR? Drag and drop is something that RN is really missing, so I'd love to see an addition like this, especially now that Reanimated 2 is out. Thanks so much!

2024-10-15 15:48 UTC, j-piasecki commented
Since the other PR regarding DragGestureHandler was closed, I think this one can be closed as well.

2024-10-15 15:48 UTC, closed without merging