add optional speed parameter to open/closeDrawer that is then passed …
software-mansion/react-native-gesture-handler pull request #1133
Opened 2020-07-17 22:39 UTC by jeremywho

## Description

I want to control the speed with which the drawer opens/closes.

Velocity does not seem to provide this functionality. 

Adjusting the Animation.spring `speed` parameter does. 

From the RN Animation docs here: https://reactnative.dev/docs/animated#spring

> speed: Controls speed of the animation. Default 12.
> ...
> velocity: The initial velocity of the object attached to the spring. Default 0 (object is at rest).

## Test plan

I manually tested the change my using different values for speed and comparing the results on device.

2020-11-06 15:59 UTC, jakub-gonet commented on DrawerLayout.js
> +      speed: speed != null ? speed : undefined,
I think this can be written as `speed ?? undefined`

2020-11-06 16:01 UTC, jakub-gonet requested changes
Could you update the docs as well?

Besides that and my other comment everything looks great, thanks!

2020-11-13 17:41 UTC, jeremywho commented
@jakub-gonet I've update the PR. 

I took a stab at the documentation, feel free to request changes to the copy for that.

2020-11-14 18:02 UTC, jakub-gonet requested changes
Left a few inline comments.

Please add some small example to test it on in the description of the PR and please change some existing example in the repo to use `speed` param if possible.

2020-11-14 18:02 UTC, jakub-gonet commented on docs/docs/component-drawer-layout.mdx
> +### `close`
```suggestion
### `closeDrawer(options)`
```

2020-11-14 18:02 UTC, jakub-gonet commented on docs/docs/component-drawer-layout.mdx
> +close can take an optional `options` parameter, enabling further customization of the close animation.
```suggestion
`closeDrawer` can take an optional `options` parameter which is an object, enabling further customization of the close animation.
```

2020-11-22 10:07 UTC, jakub-gonet commented
@jeremywho, what's the status of this?

2020-11-24 00:06 UTC, jeremywho commented
@jakub-gonet I've updated the branch.

Does the typescript definition need to be updated manually? It would be nice to have the drawer options in there.

2020-11-24 09:29 UTC, jakub-gonet commented
Yes, you'll have to extend drawer types exported from RN.

2020-11-24 16:11 UTC, jeremywho commented
Typescript def updated.

2020-11-24 16:29 UTC, jakub-gonet approved these changes
LGTM, thanks!

I can merge it after it passes the CI.

2020-11-25 12:52 UTC, merged