correct platform constants import
software-mansion/react-native-gesture-handler pull request #1211
Opened 2020-10-13 16:22 UTC by drewandre

## Description

Fixes #1210 by importing platform constants from react-native's `Platform` API instead of `NativeModules.PlatformConstants`. ForceTouchGestureHandler is the only handler that requires this file, so this change only affects this handler. It is also backwards-compatible.

I'm a bit confused why PlatformConstants would ever be used over Platform. They have a slightly different data structure, but as far as I can tell the constants are the same.

## Test plan

I tested this on the [gesture-handler example app](https://github.com/software-mansion/react-native-gesture-handler/tree/master/Example) as well as the [reanimated v2 playground repo](https://github.com/software-mansion-labs/reanimated-2-playground). I did not test on web, but PlatformConstants is not a file required by any web-specific files.

2020-10-16 08:09 UTC, jkadamczyk requested changes
Hey @drewandre 
I added a suggestion on how it can be implemented in case someone is using an older version and `PlatformConstants` is still available.
@jakub-gonet Please let me know if I'm wrong with the solution in any way 😄

2020-10-16 08:09 UTC, jkadamczyk commented on PlatformConstants.js
> +import { Platform } from 'react-native';
```suggestion
import { NativeModules, Platform } from 'react-native';

```

2020-10-16 08:09 UTC, jkadamczyk commented on PlatformConstants.js
> +export default Platform.constants;
```suggestion
export default NativeModules?.PlatformConstants ?? Platform.constants;

```

2020-10-19 07:54 UTC, jkadamczyk commented
@drewandre Thanks for the fixes, I'll try to look into this today and get it merged. Have a good day!

2020-10-21 10:42 UTC, jkadamczyk commented
E2E tests are kind of not working I have to investigate why 🤷

2021-02-09 15:37 UTC, jakub-gonet commented
Updated branch with master. Sorry for introducing a bunch of unrelated lint changes.

2021-02-12 21:53 UTC, jakub-gonet commented
CI is failing due to missing `Platform.constants` types.
I submitted https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51146 so we should update RN types after it's merged and merge this one.

2021-02-13 13:56 UTC, jakub-gonet approved these changes
Thanks!

2021-02-13 13:57 UTC, merged