Returning Swipeable reference
software-mansion/react-native-gesture-handler pull request #2105
Opened 2022-06-15 14:09 UTC by franck-nadeau

The following code allows me to do the following two things:

1. Close any previously opened Swipeable views when one is opened

````
  const openedRow = useRef();
  function renderItem({item: payable, index, separators}) {
    return (
      <Swipeable
        onSwipeableWillOpen={() => openedRow.current?.close()} // Close a previously opened row
        onSwipeableOpen={(_, swipeable) => (openedRow.current = swipeable)} // Keep a link to the currenlty
````

2. Close a Swipeable view when it is being deleted.
````
        renderRightActions={(_, __, swipeable) => {
          return (
             <TouchableOpacity
                onPress={() => {
                  swipeable.close(); // Close the Swipeable when the user presses the button
````

## Description

## Test plan

2022-06-20 12:23 UTC, j-piasecki requested changes
Hi! First of all, sorry for the delay, could you update formatting so it passes lint check?

2022-09-15 08:29 UTC, olivertylsar commented
Any updates on this one?

2022-09-20 11:08 UTC, j-piasecki requested changes

2022-09-20 11:08 UTC, j-piasecki commented on src/components/Swipeable.tsx
> +    swipeable: Swipeable,
```suggestion
    swipeable: Swipeable
```

2022-09-20 11:08 UTC, j-piasecki commented on src/components/Swipeable.tsx
> +  onSwipeableClose?: (direction: 'left' | 'right', swipeable: Swipeable) => void;
```suggestion
  onSwipeableClose?: (
    direction: 'left' | 'right',
    swipeable: Swipeable
  ) => void;
```

2022-09-20 11:08 UTC, j-piasecki commented on src/components/Swipeable.tsx
> +  onSwipeableOpen?: (direction: 'left' | 'right', swipeable: Swipeable) => void;
```suggestion
  onSwipeableOpen?: (
    direction: 'left' | 'right',
    swipeable: Swipeable
  ) => void;
```

2022-09-20 11:11 UTC, j-piasecki commented on src/components/Swipeable.tsx
> +  ) => void;
```suggestion
  onSwipeableOpen?: (direction: 'left' | 'right', swipeable: Swipeable) => void;
```

2022-09-20 12:17 UTC, j-piasecki approved these changes
I haven't noticed I can edit your PR, sorry for the delay.

2022-09-20 12:18 UTC, merged

2024-03-17 14:18 UTC, Sotatek-QuanDo commented
Excuse me, isn't it ip you opened row 1 and close it, when you open it again, it will auto close? I'm facing this issue right now

2024-12-18 10:15 UTC, sueasueasuea commented
> Excuse me, isn't it ip you opened row 1 and close it, when you open it again, it will auto close? I'm facing this issue right now

I facing the same issue
when swipe to open then close it
swipe to open again then it close itself.
Please fix this issue.
@franck-nadeau