fix: RCT_NEW_ARCH_ENABLED=0 to disable new arch
software-mansion/react-native-gesture-handler pull request #2178
Opened 2022-08-23 10:16 UTC by nomi9995

## Description
`RCT_NEW_ARCH_ENABLED=0` is not working, sometimes disturb when we enable and disable the new arch

## Test plan
`RCT_NEW_ARCH_ENABLED=1` enable new arch and then try to disable `RCT_NEW_ARCH_ENABLED=0` then you will get this error `react/renderer/components/rngesturehandler/Props.h failed`

2022-08-23 13:30 UTC, tomekzaw requested changes

2022-08-23 13:30 UTC, tomekzaw commented on RNGestureHandler.podspec
> +fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED']=='1'
```suggestion
fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

2022-08-24 07:57 UTC, j-piasecki approved these changes

2022-08-24 07:57 UTC, tomekzaw approved these changes

2022-08-24 07:57 UTC, merged