Make macOS codepath less chatty
software-mansion/react-native-gesture-handler pull request #2193
Opened 2022-08-31 11:42 UTC by hsjoberg

## Description

Hey.
This is just a small fix for the react-native-macos target.
It's a bit chatty right now, for no good reason (I mistakenly copied this over from the web target).

Everything the user clicks (in debug builds), this will show up, because of how reeact-native handles `console.warn`.
![image](https://user-images.githubusercontent.com/3824379/187670490-ce5055dd-37dc-4d46-9f11-719d2fb96923.png)

2022-09-05 07:26 UTC, j-piasecki requested changes
Could you add comments in those functions, making them no longer empty, to satisfy eslint?

2022-09-05 07:26 UTC, j-piasecki commented on src/RNGestureHandlerModule.macos.ts
> +  handleSetJSResponder(_tag: number, _blockNativeResponder: boolean) {},
```suggestion
  handleSetJSResponder(_tag: number, _blockNativeResponder: boolean) {
    // NO-OP
  },
```

2022-09-05 07:26 UTC, j-piasecki commented on src/RNGestureHandlerModule.macos.ts
> +  handleClearJSResponder() {},
```suggestion
  handleClearJSResponder() {
    // NO-OP
  },
```

2022-09-20 11:05 UTC, j-piasecki approved these changes
Seems like I could do it myself, didn't notice it. Sorry for the delay 😅.

2022-09-20 11:05 UTC, merged

2022-09-20 12:18 UTC, hsjoberg commented
> Sorry for the delay 😅.

@j-piasecki No worries. Sorry myself. I became busy and occupied with other things 😅