feat: new onSwipeableOpenDragStart and onSwipeableCloseDragStart events
software-mansion/react-native-gesture-handler pull request #2589
Opened 2023-09-16 14:45 UTC by rampazzo1989

## Description

## Test plan

2023-09-18 12:29 UTC, matheusinfo commented
That would be great, i already had this problem on my app and had to fix it manually with patch

2023-09-20 08:28 UTC, m-bert requested changes
Hi @rampazzo1989, thanks for this PR! It looks ok, but I'd like you to make some cosmetic changes, so I've left some comments.

2023-09-20 08:28 UTC, m-bert commented on src/components/Swipeable.tsx
> +      const translationX = (dragX + DRAG_TOSS * velocityX) / friction!;
```suggestion
      const { velocityX, translationX: dragX } = ev.nativeEvent;
      const { rowState } = this.state;
      const { friction } = this.props;
      
      const translationX = (dragX + DRAG_TOSS * velocityX) / friction!;
```

2023-09-20 08:28 UTC, m-bert commented on src/components/Swipeable.tsx
> +      }
```suggestion
      const direction =
        rowState === -1
          ? 'right'
          : rowState === 1
          ? 'left'
          : translationX > 0
          ? 'left'
          : 'right';
```

2023-09-20 08:28 UTC, m-bert commented on src/components/Swipeable.tsx
> +    }
```suggestion
      if (rowState === 0) {
        this.props.onSwipeableOpenStartDrag?.(direction);
      } else {
        this.props.onSwipeableCloseStartDrag?.(direction);
      }
```

2023-09-20 13:15 UTC, rampazzo1989 commented
> Hi @rampazzo1989, thanks for this PR! It looks ok, but I'd like you to make some cosmetic changes, so I've left some comments.

Thank you for the review @m-bert! I've done the changes, really got better!

2023-09-20 13:29 UTC, m-bert approved these changes

2023-09-20 13:29 UTC, m-bert commented on src/components/Swipeable.tsx
> +    if (ev.nativeEvent.state === State.ACTIVE) {
```suggestion

    if (ev.nativeEvent.state === State.ACTIVE) {
```

2023-09-20 13:32 UTC, m-bert commented
Now it looks much better, thank you once again! :white_check_mark:

2023-09-20 13:34 UTC, merged

2024-10-11 12:15 UTC, latekvo commented
Hey @rampazzo1989,

when working on `ReanimatedSwipeable`, i encountered this part of your code:

```js
const direction =
  rowState === -1
    ? 'right'
    : rowState === 1
    ? 'left'
    : translationX > 0
    ? 'left'
    : 'right';
```

When swiping to the left when the `left` panel is open, it returns `left`, but when swiping to the left when no panels are open, it returns `right`.

So when returning `left` and `right` to the callback, was your intention to return the swipe direction or the side of the panel that would be opened?

On another note, do you think the callbacks should always receive the swiping direction like they do when no panels are open, or should it stay how it is, with swiping direction returned always being `right` when `right` panel is open, and `left` when `left` one is?