fix: Add support for borderRadii on RectButton
software-mansion/react-native-gesture-handler pull request #2691
Opened 2023-12-12 10:25 UTC by kacperkapusciak

2023-12-14 10:51 UTC, m-bert approved these changes
Logic looks fine, thanks for fixing that! ❤️  

I'll leave review of TS part for @tjzel

2023-12-14 13:13 UTC, tjzel approved these changes
TS seems approvable now 🚀

2023-12-18 10:01 UTC, j-piasecki requested changes

2023-12-18 10:01 UTC, j-piasecki commented on src/components/splitStyleProp.ts
> +}
1. Umm, do we care about `borderTopWidth`, `borderRightWidth`, ...?
2. It's better that now, so should we?

2024-01-11 11:52 UTC, j-piasecki commented on src/components/splitStyleProp.ts
> +}
I'll assume that this comment being ignored by @kacperkapusciak means something along the lines of `and who is that? mr. grouchy, destroyer of good fun, slayer of children's smiles` and we'll figure it out in the due time.

2024-01-11 11:54 UTC, j-piasecki approved these changes
🔥

2024-01-11 11:54 UTC, merged

2025-04-09 12:47 UTC, versten1uk commented
Still reproduced in `2.24.0`