Add rotation and pinch velocity on macOS
software-mansion/react-native-gesture-handler pull request #2706
Opened 2023-12-20 15:52 UTC by jfedak

## Description

## Test plan

2024-01-11 15:32 UTC, j-piasecki commented on apple/Handlers/RNPinchHandler.m
> +  _velocity = (self.magnification - prevMagnification) / (event.timestamp - prevTime);
To double-check, what's the unit of `event.timestamp`? On iOS the unit of timer is device-dependant (https://github.com/software-mansion/react-native-gesture-handler/blob/db51032fcd0f81449736564e2f3fd055f29a28a4/apple/Handlers/RNLongPressHandler.m#L117).

2024-01-25 10:16 UTC, j-piasecki commented on apple/Handlers/RNPinchHandler.m
> +  _velocity = (self.magnification - prevMagnification) / (event.timestamp - prevTime);
Then the time delta should be multiplied by `1000` (both here and in the rotation handler), on Android the time unit we're using is milliseconds.

2024-01-31 13:06 UTC, m-bert requested changes

2024-01-31 13:06 UTC, m-bert commented on apple/Handlers/RNRotationHandler.m
> +  _velocity = (self.rotation - prevRotation) / (event.timestamp - prevTime);
This delta should also be multiplied by `1000`, right?

2024-02-08 07:07 UTC, m-bert approved these changes
🟢

2024-02-08 16:02 UTC, merged