Restyle Gesture Handler Documentation
software-mansion/react-native-gesture-handler pull request #2753
Opened 2024-02-08 12:42 UTC by patrycjakalinska

New branch with fixed Docusaurus - changes include that done [prior PR.](https://github.com/software-mansion/react-native-gesture-handler/pull/2737)

Additionally:
* Add `Playground` with examples: Pan, Tap, Rotation, Fling, LongPress and Pinch
* Add dark mode
* Make landing page responsive and well-adjusted for mobile, tablet, laptop and laptop+ dimensions
* Add reusable components: `HomepageButton` and `InteractiveExampleComponent`

2024-02-09 10:24 UTC, kacperkapusciak requested changes

2024-02-09 10:24 UTC, kacperkapusciak commented on docs/src/components/GestureExamples/TapExample/index.tsx
> +    //   : '8px solid var(--swm-purple-light-80)',
```suggestion
```
remove dead code

2024-02-09 10:24 UTC, kacperkapusciak commented on docs/src/components/GestureFeatures/GestureFeatureList/index.tsx
> +  },
```suggestion
  {
    title: 'native gesture recognizers',
    body: 'With Gesture Handler touch stream handling happens on the UI thread and uses APIs native to each platform.',
  },
  {
    title: 'native components',
    body: 'Gesture Handler library ships with a set of components that aims to provide best possible interations such as SwipeableRow or Drawer.',
  },
  {
    title: '120 FPS',
    body: 'Gesture Handler integrates tightly with Reanimated to allow you to build smooth gesture based experiences up to 120 fps.',
  },
```

2024-02-09 11:47 UTC, patrycjakalinska commented on docs/package.json
> +  "private": false,
It was changed to test something on mobile, my bad

2024-02-14 14:33 UTC, kacperkapusciak requested changes
<img width="1097" alt="image" src="https://github.com/software-mansion/react-native-gesture-handler/assets/39658211/e425dd1f-4fe1-4ca4-9af5-8730fa0c5b1c">


it looks like the images of hands have incorrect fingers for most of the gestures
- pan should have 1 finger
- tap should have 1 finger
- rotate should either have 2 fingers, the arrow is perfect
- fling is ok
- longpress should have 1 finger
- pinch is perfect

2024-02-14 14:33 UTC, kacperkapusciak commented on docs/src/components/GestureExamples/FlingExample/index.tsx
> +      if (endPositionY.value === 0) endPositionY.value = e.y;
```suggestion
    .onStart((e) => {
      endPositionX.value = e.x;
      endPositionY.value = e.y;
```
please make this change to make it work a little bit more smooth

2024-02-14 14:33 UTC, kacperkapusciak commented on docs/src/components/GestureExamples/PanExample/index.tsx
> +    .onEnd(() => setShowHand(true));
```suggestion
    .onEnd(() => setShowHand(true))
    .minDistance(0);
```
add this here to make it more responsive

2024-02-14 14:33 UTC, kacperkapusciak commented on docs/src/components/GestureExamples/TapExample/index.tsx
> +    transform: [{ scale: withTiming(pressed.value ? 1.2 : 1) }],
```suggestion
    transform: [{ scale: withTiming(pressed.value ? 1.8 : 1) }],
```
lets make it a bit bigger coz I have big fingers that fully cover the button :)

2024-02-14 14:33 UTC, kacperkapusciak commented on docs/src/components/GestureExamples/LongPressExample/index.tsx
> +    transform: [{ scale: withTiming(pressed.value ? 1.2 : 1) }],
```suggestion
    transform: [{ scale: withTiming(pressed.value ? 1.8 : 1) }],
```
lets make it a bit bigger coz I have big fingers that fully cover the button :)

2024-02-14 14:37 UTC, kacperkapusciak requested changes
the version switch is missing so there's no way to change the docs version to v1 in the UI
<img width="204" alt="Screenshot 2024-02-14 at 15 35 33" src="https://github.com/software-mansion/react-native-gesture-handler/assets/39658211/ffc51fb3-5ab7-4a37-8114-5038346b7a27">

2024-02-14 14:43 UTC, kacperkapusciak commented
I also don't like the fact the theme switcher is in an arbitrary spot on the landing page.
https://github.com/software-mansion/react-native-gesture-handler/assets/39658211/7c319298-605a-4260-b492-23f8763cbf45

Can we move it to the right hand side the same it is in the docs? 🙏

2024-02-15 14:13 UTC, kacperkapusciak commented on docs/src/components/GesturePlayground/index.tsx
> +          Hover over cards to see our interaction.
```suggestion
          Tap and drag the circles to explore the gestures.
```

2024-02-16 14:38 UTC, kacperkapusciak approved these changes
LGTM :shipit:

2024-02-16 14:41 UTC, merged