Fix Android native buttons emitting 2 press events when talkbalk is enabled
software-mansion/react-native-gesture-handler pull request #3002
Opened 2024-07-23 07:48 UTC by latekvo

## Description

When talkbalk accessability mode is enabled, pressing on any of the buttons provided by gesture handler (`BaseButton`, `RawButton`, `BorderlessButton`, Et Cetera) will cause 2 separate press events to go off.

This PR fixes that invalid behaviour.

Closes: #2808 

## Test plan

- enable talkback mode
- run the attached example
- see how buttons labeled `BorderlessButton` and `BaseButton` emit 2 press events to the standard output

## Attached example

```js
import React from 'react';
import { BaseButton } from 'react-native-gesture-handler';
import { Text, View, StyleSheet } from 'react-native';

const press = () => console.log('JS pressed');
const touch = () => console.log('JS touch');

export default function App() {
  return (
    <View style={styles.root}>
      <BaseButton onPress={press}>
        <View
          accessible
          accessibilityRole="button"
          style={styles.button}
          onTouchStart={touch}>
          <Text>BaseButton</Text>
        </View>
      </BaseButton>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    justifyContent: 'center',
    flex: 1,
  },
  button: {
    width: 200,
    height: 100,
    margin: 20,
    backgroundColor: 'cyan',
  },
});
```

2024-07-23 09:20 UTC, latekvo commented
Please ignore the linter issues for now, I'm working on getting openjdk running.

2024-07-24 12:32 UTC, m-bert requested changes
Looks good, but I think we should wait for @j-piasecki opinion 😅

2024-07-24 12:32 UTC, m-bert commented on android/src/main/java/com/swmansion/gesturehandler/core/NativeViewGestureHandler.kt
> +      // which is UNDETERMINED when receiving the invalid event, and BEGAN when receiving the valid one.
Please update this comment as it doesn't check `state` anymore 😅

2024-07-24 13:07 UTC, j-piasecki approved these changes

2024-07-24 13:09 UTC, m-bert approved these changes

2024-07-24 13:42 UTC, merged